services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_USERNAME: jira
      DB_PASSWORD: JiraRush
      DB_URL: jdbc:postgresql://db:5432/jira
      GITHUB_CLIENT_ID: 3d0d8738e65881fff266
      GITHUB_CLIENT_SECRET: 0f97031ce6178b7dfb67a6af587f37e222a16120
      GOOGLE_CLIENT_ID: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GITLAB_CLIENT_ID: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
      GITLAB_CLIENT_SECRET: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
      MAIL_HOST: smtp.gmail.com
      MAIL_USERNAME: jira4jr@gmail.com
      MAIL_PASSWORD: zdfzsrqvgimldzyj
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nginx

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf